# Generated by Django 3.2.8 on 2021-10-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_products_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='feature',
            field=models.BooleanField(default=True),
        ),
    ]
